Optimize Social Query for activities, first phase
exo-addons/social-rdbms pull request #14
Opened 2016-10-07 08:05 UTC by boubaker

This PR will improve the activities queries and will avoid using a java query builder instead of NamedQuery. In fact, java query builder is CPU consumer and uses some blocker operations.
The first commits will be to improve the JPQL queries and a second commit will be added to delete the Query Builder and replace it by NamedQueries.

2016-10-07 08:49 UTC, thomasdelhomenie requested changes
Can you explain what you did in this PR please ?

2016-10-07 08:49 UTC, thomasdelhomenie commented on lib/src/main/java/org/exoplatform/social/addons/storage/RDBMSActivityStorageImpl.java
> +    ExoSocialActivity updatedActivity = getActivity(existingActivity.getId());
Is this change really related to the PR ? It seems to revert the fix https://github.com/exo-addons/social-rdbms/commit/22b61aeab8e6e8ca9754032728ffd7e5bc63767e

2016-10-07 08:51 UTC, thomasdelhomenie commented
I mean from a query point of view. I see you splitted the query to retrieve the connections in 2 queries (sender and receiver).

2016-10-07 10:48 UTC, boubaker commented on lib/src/main/java/org/exoplatform/social/addons/storage/RDBMSActivityStorageImpl.java
> +    ExoSocialActivity updatedActivity = getActivity(existingActivity.getId());
Nope, my bad.

2016-10-21 12:23 UTC, thomasdelhomenie commented
Social RDBMS addon has been merged in Social project. Please move your PR.
Do we have a Jira issue for this PR ?

2016-10-21 14:07 UTC, boubaker commented
Yep, I have added in title the JIRA issue: SOC-5515

2016-10-23 14:02 UTC, boubaker commented
moved to social project
https://github.com/exodev/social/pull/112

2016-10-23 14:02 UTC, closed without merging