SOC-5361: use ES for connection page
exo-addons/social-rdbms pull request #16
Opened 2016-10-10 07:43 UTC by nttuyen

optimize a little on query searching in identity and use ES for search in connections instead of JPA query

2016-10-10 07:56 UTC, thomasdelhomenie requested changes

2016-10-10 07:56 UTC, thomasdelhomenie commented on lib/src/main/java/org/exoplatform/social/addons/search/ProfileSearchConnector.java
> +        result = "incomings";
Does not look very logical :) Not a mistake ? Can you explain ?

Also, we should probably have an enum here with a value : CONFIRMED("connections")

2016-10-10 07:56 UTC, thomasdelhomenie commented on lib/src/main/java/org/exoplatform/social/addons/storage/RDBMSRelationshipStorageImpl.java
> +    //return searchConnectionByFilter(existingIdentity, Type.CONFIRMED, profileFilter, offset, limit);
Remove comments

2016-10-10 07:56 UTC, thomasdelhomenie commented on lib/src/main/java/org/exoplatform/social/addons/storage/dao/jpa/query/ProfileQueryBuilder.java
> +      List<Identity> excludes = filter.getExcludedIdentityList();
Please add comments to explain the steps of the query build.

2016-10-10 08:18 UTC, nttuyen commented on lib/src/main/java/org/exoplatform/social/addons/search/ProfileSearchConnector.java
> +        result = "incomings";
Actually the field "outgoing" contains all IDs of Identities who receive the connection request from current user. When userA sends a request connect to userB then userA will be contained on "incoming" field of userB and userB will be contained on "outgoing" field of userA.

So, If we want to search on "outgoing" of a people, we have to search on all Identities who contain his ID on their "incoming" field. That's why I reverse the "incoming" and "outgoing".

2016-10-10 09:39 UTC, nttuyen commented
PR was updated, please review again @thomasdelhomenie.

2016-10-10 11:31 UTC, thomasdelhomenie commented on lib/src/main/java/org/exoplatform/social/addons/search/ProfileSearchConnector.java
> +        result = "incomings";
ok, got it, thanks

2016-10-21 12:26 UTC, thomasdelhomenie commented
Using ES for connections search will be done in https://github.com/exo-addons/social-rdbms/pull/7.
I close this one.
@nttuyen can you have a look at the PR https://github.com/exo-addons/social-rdbms/pull/7 to check if it includes what you have done in this PR please ?

2016-10-21 12:26 UTC, closed without merging