SOC-5361 [social-rdbms] My connection page is too slow
exo-addons/social-rdbms pull request #18
Opened 2016-10-16 18:38 UTC by boubaker

* Move Common Transformation operations (Entity to DTO) into Utils class to simplify transformations in all DAO and avoid getting DTO from top layer services
* Transform List to Set in order ot be able to fetch multiple collections at the same time using JPQL
* Fix the identities count in AllPeople page and modify query to retrieve identities with relationship at the same time in same DTO
* Modify Connections queries to use NamedQueries instead of building query when possible (with minimal modifications).

2016-10-17 08:45 UTC, thomasdelhomenie requested changes

2016-10-17 09:46 UTC, boubaker commented on lib/src/main/java/org/exoplatform/social/addons/storage/entity/IdentityEntity.java
> +                "     AND identity.id != :identityId " +
Done, thanks.

2016-10-17 09:46 UTC, boubaker commented on lib/src/main/java/org/exoplatform/social/addons/storage/entity/IdentityEntity.java
> +                "     AND identity.providerId= :providerId "
Done, thanks.

2016-10-17 09:47 UTC, boubaker commented on lib/src/main/java/org/exoplatform/social/addons/storage/Utils.java
> +public class Utils {
Done, thanks. (EntityConverterUtils, Utils is used to know that it's an utility class with static methods)

2016-10-17 09:47 UTC, boubaker commented on lib/src/main/java/org/exoplatform/social/addons/storage/RDBMSRelationshipStorageImpl.java
> +    // FIXME: Sorting is not applied,
Done, thanks.

2016-10-18 14:47 UTC, thomasdelhomenie approved these changes

2016-10-19 08:16 UTC, boubaker commented
Merged

2016-10-19 08:16 UTC, closed without merging